ROOT_DIR: "/home/cube/development/projects/price_tracker"
BASE_DIR: "datasets/base"
STAGING_DIR: "datasets/staging"
sources: [jumia, carrefour] #, mamababyshop]

jumia:
  schema:
    datetime: [created_at]
    integer: [prev_price, price, voters]
    float: [discount, ratine]
    string: [brand, category, item_url, name, sku]

carrefour:
  schema:
    datetime: [created_at]
    integer: [price, no_of_stock]
    string:
      [
        sku,
        category,
        name,
        brand,
        item_size,
        category_hierarchy,
        item_url,
        origin,
        supplier,
        type,
        availability_status,
        availability_max,
        item_type,
        stock_status,
        source_id,
      ]
# mydawa:
#   schema:
#     datetime: [created_at]
#     integer: [prev_price, price, voters]
#     float: [discount, ratine]
#     string: [brand, category, item_url, name, sku]

# mamababyshop:
#   schema:
#     datetime: [created_at]
#     integer: [price, voters]
#     float: [discount, rating]
#     string: [category, item_url, name, stock_status]
